//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaRH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pessoa
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public Nullable<System.DateTime> DataNascimento { get; set; }
        public Nullable<bool> TipoBancario { get; set; }
        public Nullable<int> Agencia { get; set; }
        public Nullable<int> Conta { get; set; }
        public string TipoConta { get; set; }
        public string ChavePix { get; set; }
    }
}
